#Author: Alexey Usov (dax@xdax.ru, https://t.me/doubleaxe, https://github.com/doubleaxe)
#Please don't remove author reference from this file
rules:
    #ts specific
    brace-style: off
    "@typescript-eslint/brace-style": ["error", "1tbs", { "allowSingleLine": true }]
    comma-dangle: off
    "@typescript-eslint/comma-dangle": ["error", "always-multiline"]
    comma-spacing: off
    "@typescript-eslint/comma-spacing": "error"
    func-call-spacing: off
    "@typescript-eslint/func-call-spacing": ["error", "never"]
    indent: off
    "@typescript-eslint/indent": ["warn", 4, { "MemberExpression": "off", "SwitchCase": 1 }]
    keyword-spacing: "off"
    "@typescript-eslint/keyword-spacing": ["error", {
        before: true,
        after: true,
        overrides: {
            catch: { after: false },
            for: { after: false },
            if: { after: false },
            switch: { after: false },
            while: { after: false },
        }
    }]
    "@typescript-eslint/member-delimiter-style": "error"
    object-curly-spacing: off
    "@typescript-eslint/object-curly-spacing": ["error", "never"]
    quotes: off
    "@typescript-eslint/quotes": ["error", "single", { "avoidEscape": true }]
    semi: off
    "@typescript-eslint/semi": ["error", "always"]
    space-before-blocks: off
    "@typescript-eslint/space-before-blocks": ["error", "always"]
    space-before-function-paren: off
    "@typescript-eslint/space-before-function-paren": ["error", "never"]
    space-infix-ops: off
    "@typescript-eslint/space-infix-ops": "error"
    "@typescript-eslint/type-annotation-spacing": "error"
