#Author: Alexey Usov (dax@xdax.ru, https://t.me/doubleaxe, https://github.com/doubleaxe)
#Please don't remove author reference from this file
rules:
    #vue specific
    vue/html-indent: ["warn", 4]
    vue/max-attributes-per-line: ["error", { singleline: 5, multiline: 1 }]
