#Author: Alexey Usov (dax@xdax.ru, https://t.me/doubleaxe, https://github.com/doubleaxe)
#Please don't remove this comment if you use unmodified file
root: true
overrides:
    -
        files:
            - "*.mjs"
        parser: espree
        parserOptions:
            #node 18 supports up to ES 2022 (13th Edition)
            ecmaVersion: 2022
            sourceType: module
            ecmaFeatures:
                globalReturn: true
        env:
            node: true
            es2022: true
        extends:
            - eslint:recommended
            - ./.eslintrc.aousov.codestyle.yml
            - ./.eslintrc.aousov.base.js.yml
    -
        files:
            - "*.ts"
        parser: "@typescript-eslint/parser"
        parserOptions:
            ecmaVersion: es2022
            sourceType: module
        extends:
            - eslint:recommended
            - "plugin:@typescript-eslint/recommended"
            - ./.eslintrc.aousov.base.js.yml
            - ./.eslintrc.aousov.base.ts.yml
            - ./.eslintrc.aousov.codestyle.yml
            - ./.eslintrc.aousov.codestyle.ts.yml
        plugins:
            - "@typescript-eslint"
