rules:
    array-bracket-spacing: ["error", "never"]
    brace-style: ["error", "1tbs", { "allowSingleLine": true }]
    comma-dangle: ["error", "only-multiline"]
    dot-location: ["error", "property"]
    eol-last: ["error", "always"]
    func-call-spacing: ["error", "never"]
    indent: ["warn", 4, { "MemberExpression": "off", "SwitchCase": 1 }]
    linebreak-style: ["error", "unix"]
    max-statements-per-line: ["error", { "max": 3 }]
    new-parens: "error"
    no-multi-spaces: ["error", { "ignoreEOLComments": true }]
    no-trailing-spaces: ["error"]
    object-curly-newline: ["error", { "consistent": true }]
    object-curly-spacing: ["error", "never"]
    quotes: ["error", "single", { "avoidEscape": true }]
    semi-spacing: "error"
    #warning!
    #older semi doesn't work with CRLF files
    #if you see error (Invalid position given by 'semi') convert file to LF
    semi: ["error", "always"]
    space-before-function-paren: ["error", "never"]
    space-in-parens: ["error", "never"]
    switch-colon-spacing: "error"
