rules:
    #ts specific
    no-shadow: off
    "@typescript-eslint/no-shadow": "error"
    #no-throw-literal: off
    #"@typescript-eslint/no-throw-literal": "error"
    no-unused-vars: off
    "@typescript-eslint/no-unused-vars": ["error", { "args": "none" }]
    no-use-before-define: "off"
    "@typescript-eslint/no-use-before-define": ["error", { "functions": false, "classes": false, "typedefs": false }]
