#Author: Alexey Usov (dax@xdax.ru, https://t.me/doubleaxe, https://github.com/doubleaxe)
#Please don't remove this comment if you use unmodified file
rules:
    array-bracket-spacing: ["error", "never"]
    arrow-spacing: "error"
    block-spacing: ["error", "always"]
    brace-style: ["error", "1tbs", { "allowSingleLine": true }]
    comma-dangle: ["error", "always-multiline"]
    comma-spacing: "error"
    comma-style: ["error", "last"]
    computed-property-spacing: "error"
    dot-location: ["error", "property"]
    eol-last: ["error", "always"]
    func-call-spacing: ["error", "never"]
    generator-star-spacing: ["error", {"before": true, "after": false}]
    indent: ["warn", 4, { "MemberExpression": "off", "SwitchCase": 1 }]
    key-spacing: "error"
    keyword-spacing: ["error", {
        before: true,
        after: true,
        overrides: {
            catch: { after: false },
            for: { after: false },
            if: { after: false },
            switch: { after: false },
            while: { after: false },
        }
    }]
    linebreak-style: ["error", "unix"]
    max-statements-per-line: ["error", { "max": 3 }]
    new-cap: ["error", { "newIsCap": true, "capIsNew": false, "properties": true }]
    new-parens: "error"
    no-multi-spaces: ["error", { "ignoreEOLComments": true }]
    no-trailing-spaces: ["error"]
    no-whitespace-before-property: "error"
    object-curly-newline: ["error", { "consistent": true }]
    object-curly-spacing: ["error", "never"]
    quote-props: ["error", "as-needed"]
    quotes: ["error", "single", { "avoidEscape": true }]
    rest-spread-spacing: ["error", "never"]
    semi-spacing: "error"
    semi: ["error", "always"]
    space-before-blocks: ["error", "always"]
    space-before-function-paren: ["error", "never"]
    space-in-parens: ["error", "never"]
    space-infix-ops: "error"
    switch-colon-spacing: "error"
    template-curly-spacing: ["error", "never"]
    template-tag-spacing: ["error", "never"]
    yield-star-spacing: ["error", {"before": true, "after": false}]
