#Author: Alexey Usov (dax@xdax.ru, https://t.me/doubleaxe, https://github.com/doubleaxe)
#Please don't remove this comment if you use unmodified file
root: true
parser: vue-eslint-parser
parserOptions:
    parser: "@typescript-eslint/parser"
    ecmaVersion: es2022
env:
    browser: true
    es2022: true
extends:
    - plugin:vue/vue3-recommended
    - eslint:recommended
    - "@vue/typescript/recommended"
    - ../.eslintrc.aousov.base.js.yml
    - ../.eslintrc.aousov.base.ts.yml
    - ../.eslintrc.aousov.codestyle.yml
    - ../.eslintrc.aousov.codestyle.vue.yml
    - ../.eslintrc.aousov.codestyle.ts.yml
plugins:
    - "@typescript-eslint"
