name: Build and Deploy Release
on:
  push:
    tags:
      - v1.*
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: "deploy"
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: |
          npm run build
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: daxfb-calculator-pages
          path: dist
      - name: Zip release artifact
        run: |
          zip -r daxfb-calculator.zip *
        working-directory: dist
      - name: Upload release artifact
        uses: actions/upload-artifact@v3
        with:
          name: daxfb-calculator-release
          path: dist/daxfb-calculator.zip
          retention-days: 1
  deploy-pages:
    needs: build
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy GitHub pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          artifact_name: daxfb-calculator-pages
  deploy-release:
    if: github.event_name == 'push'
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Download release artifact
        uses: actions/download-artifact@v3
        with:
          name: daxfb-calculator-release
          path: ~/daxfb-calculator-${{ env.RELEASE_TAG }}.zip
      - name: Check artifact
        run: |
          ls -l ~
          unzip -t ~/daxfb-calculator-${{ env.RELEASE_TAG }}.zip
      - name: Build changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          commitMode: true
      - name: Create release
        uses: softprops/action-gh-release@v0.1.15
        with:
          draft: true
          prerelease: false
          generate_release_notes: false
          body: ${{ steps.github_release.outputs.changelog }}
          files: |
            ~/daxfb-calculator-${{ env.RELEASE_TAG }}.zip
